<simple_seq>          ::= <DIGIT> | <DIGIT><ws><simple_seq>
<int>                 ::= <DIGIT>
<zero>                ::= 0
<DIGIT>               ::= [0-9]
<digit1_9>            ::= [1-9]
<ws>                  ::= " "

