<slow_seq>            ::= <simple_slow_seq> | "<"<ws><slow_seq><ws><simple_slow_seq><ws>">" | "<"<ws><simple_slow_seq><ws><slow_seq><ws>">"
<simple_slow_seq>     ::= "<"<simple_seq>">"
<simple_seq>          ::= <DIGIT> | <DIGIT><ws><simple_seq>
<int>                 ::= <DIGIT>
<zero>                ::= 0
<DIGIT>               ::= 0|1|2|3|4|5|6|7|8|9
<digit1_9>            ::= 1|2|3|4|5|6|7|9
<ws>                  ::= " "

